### ISSUE TITLE
Recursive Fixing Logic is incorrect

### ISSUE THREAD

**Issue by rhnvrm** [kalbhor/MusicRepair#21]
Suppose you have a tree like:

![screenshot from 2016-12-19 22-45-07](https://cloud.githubusercontent.com/assets/952036/21321919/d9caadae-c63c-11e6-8c5f-c3722c40b244.png)

Music repair will only fix I Hate U, I Love U by Gnash.

**Comment by kalbhor** [comment]
```
            for dirpath, _, _ in walk('.'):
                chdir(dirpath)
                revert_music()
```
chdir is a wrong method, since after getting into first nested directory, musicrepair can't go into the second nested directory. Thanks for pointing this out. I'll rather pass in the path's of the folders as arguments to rever_music() than change directories altogether.

**Comment by rhnvrm** [comment]
@lakshaykalbhor: I'm working on a fix, and will send a PR in a few minutes.
