### ISSUE TITLE
!

### ISSUE THREAD

**Issue by Droyk** [kalbhor/MusicRepair#23]

**Comment by kalbhor** [comment]
Type this on your cmd and tell me what message you get `pip install musicrepair`

**Comment by Droyk** [comment]
Okay here is the result
```
Requirement already satisfied: musicrepair in c:\program files\python35\lib\site-packages\musicrepair-5.8-py3.5.egg
Requirement already satisfied: bs4 in c:\program files\python35\lib\site-packages (from musicrepair)
Requirement already satisfied: colorama in c:\program files\python35\lib\site-packages\colorama-0.3.7-py3.5.egg (from musicrepair)
Requirement already satisfied: mutagen in c:\program files\python35\lib\site-packages\mutagen-1.35.1-py3.5.egg (from musicrepair)
Requirement already satisfied: spotipy in c:\program files\python35\lib\site-packages\spotipy-2.3.8-py3.5.egg (from musicrepair)
Requirement already satisfied: six in c:\program files\python35\lib\site-packages\six-1.10.0-py3.5.egg (from musicrepair)
Requirement already satisfied: requests in c:\program files\python35\lib\site-packages\requests-2.12.4-py3.5.egg (from musicrepair)
Requirement already satisfied: beautifulsoup4 in c:\program files\python35\lib\site-packages (from bs4->musicrepair)
```

**Comment by kalbhor** [comment]
That means that musicrepair has been installed. Just type `musicrepair -h` in your cmd to read the help menu and then use musicrepair as you desire.

**Comment by Droyk** [comment]
I have some questions for you 
I like gui applications because I don't have much experience with command line and user don't need any experience to something in gui it's easy and it just too annoying to write every command on a cmd 
so why you didn't create a gui application for music repair well I know it's totally your wish what you want to create ... SO I want to ask is there is anyway I can build a gui out of this.. (and for the fact I just started learning coding it's only been 5 days since I started learning coding write now I learning css+html5 is there is anyway a novice like me be able to create a gui for this application if yes then will you be able to tell me how?)

2nd question I want to ask is did I install your music repair rightway or not?
as I said above 

- what I did was first I downloaded music repair which gave me zip file and I extract that on desktop and 

- then install Python 3.5.2 x64 and after that I open cmd and type command python setup.py install
I didn't feel like I got the result so then I tried pip3 install musicrepair and after that I asked your help!!

plz tell me what I did wrong and what should I be doing first 

3rd question in github I saw many setup.py files so that means if I install those setup.py files I will only get commandline file or some have a gui file too.

**Comment by kalbhor** [comment]
@Droyk 
To answer your first question, I believe you should continue and successfully complete whatever tutorial/course you're taking in html5 and css and not dabble in something you're not clear with as it'll only confuse you more. 
Second, I have uploaded musicrepair on PyPI which is a package manager. Meaning all you need to do is type `pip install (module name)` to install such packages. 
I don't believe that currently there's a requirement for a GUI version.

**Comment by Droyk** [comment]
> Second, I have uploaded musicrepair on PyPI which is a package manager. Meaning all you need to do is type pip install (module name) to install such packages.

Okay I understood that but there many ways to install something so as I said above 

 pz tell me what this command does  python setup.py install will I be able to install music repair with this command.

**Comment by kalbhor** [comment]
You have already installed it using pip. I suggest that you google search these questions, and get familiar with coding in general before diving into this stuff

**Comment by Droyk** [comment]
>You have already installed it using pip.

I do know that I already installed it using pip command but what I want to know is there is anyother that user can install this package....
