### ISSUE TITLE
Is it obligatory to specify that key?

### ISSUE THREAD

**Issue by AlejandroC90** [kalbhor/MusicRepair#28]
How can I skip this, I don't want lyrics anyway
![image](https://cloud.githubusercontent.com/assets/5132907/25243570/16b2beb0-25c3-11e7-8ea9-f99d46dc23f5.png)

**Comment by kalbhor** [comment]
It isn't compulsory, it will display the warning but it will still work.

**Comment by AlejandroC90** [comment]
Then that means that doesn't work for me, don't know why, installed from pip.
![peek 2017-04-20 13-23](https://cloud.githubusercontent.com/assets/5132907/25246208/8f3340f4-25cc-11e7-8947-7f5bbc1801de.gif)

**Comment by kalbhor** [comment]
Try `musicrepair -d ./`. The `-d` or `--dir` is the option to choose the directory for repair.

**Comment by kalbhor** [comment]
@AlejandroC90 I have updated it on pypi to work with just `musicrepair`. Make sure you have version `6.1.3`.

**Comment by AlejandroC90** [comment]
Thanks for checking, I already updated but seems to appear another problem
![image](https://cloud.githubusercontent.com/assets/5132907/25248065/78d18a90-25d2-11e7-9cf2-2b604e2666e2.png)

**Comment by kalbhor** [comment]
@AlejandroC90 I believe if you remove that 03 number and rename your song to `Dame tu aire.mp3`, it should be able to find the results. Anyhow, I've fixed handling the error and updated to version `6.1.4`
