### ISSUE TITLE
Revert Option only deletes Tags and does not recover the old filename

### ISSUE THREAD

**Issue by userlip** [kalbhor/MusicRepair#30]
FYI: I am really sorry to post all these Issues here but I just found out about this tool today so ive been using it the whole day and its awesome!

So I had the issue, that some of the Songs werent identified correctly so I ended up with completely wrong Tags and even Names which I wanted to revert so I could atleast tag these songs on my own but unfortunately the file names stayed the same so I could not really identify the artist in some cases anymore

Thanks

**Comment by kalbhor** [comment]
If the filename has been changed now, I'm sorry there's no way to reveal the previous file name. But in future you can run `musicrepair` with the `--norename` argument. That will ensure that musicrepair doesn't touch the file names.

**Comment by kalbhor** [comment]
PS : No need to be sorry for posting these issues! I'm happy to help with any query you have. 👍
