### ISSUE TITLE
"No token provided"

### ISSUE THREAD

**Issue by maxrdu** [kalbhor/MusicRepair#31]
I'm always getting this error:
 YONAS - Live It Up (Official Video).mp3
http status: 401, code:-1 - https://api.spotify.com/v1/search?q=YONAS+Live+It+Up&limit=1&offset=0&type=track:
 No token provided
Could not find metadata
YONAS - Live It Up (Official Video)
Unkown
Unkown
i'm on windows 10 if  that helps and i enterd the api key

**Comment by kalbhor** [comment]
Its been a few months...
But I've gotten around to fixing it now. 

Update it and it should work. Go through the readme once again. 
```pip install musicrepair -U```
