### ISSUE TITLE
Error while running the program

### ISSUE THREAD

**Issue by leovarmak** [kalbhor/MusicRepair#32]
![image](https://user-images.githubusercontent.com/14135553/30000196-3c3e0626-9080-11e7-8168-406765509a49.png)

**Comment by kalbhor** [comment]
This is due to changes in Spotify's API. I'll have to make major changes in this project to fix this. If you want, go ahead send me a PR, because I'm preoccupied with other stuff currently.

Will most probably fix in like a month or so.

**Comment by Princeyadav05** [comment]
Can you guide how can this issue be fixed ?

**Comment by kalbhor** [comment]
I'll have to add a way to send Spotify API keys, thats it.

**Comment by Princeyadav05** [comment]
I really liked your script. I will be grateful if you can add the Spotify Keys.

**Comment by kalbhor** [comment]
I am currently a little preoccupied (College & all). I'll sit and fix this script in a few weeks (hopefully). 

I'm glad you really liked it! Till then, may I suggest an alternative?
[Beets](https://github.com/beetbox/beets) works really well too.

**Comment by Princeyadav05** [comment]
Thank you so much. I'll try beats. Also, I'll try to fix the issue in your script. And hopefully give a PR.

**Comment by kalbhor** [comment]
Hey guys! I've fixed musicrepair!
You'll need Spotify API credentials (Go through the readme). 

It should work as expected now :D

Make sure you update musicrepair (```pip install musicrepair -U```)

(Closing issue, reopen if any problems persist)

**Comment by privatadata** [comment]
Is this project dead?
