### ISSUE TITLE
musicrepair error

### ISSUE THREAD

**Issue by beaud37210** [kalbhor/MusicRepair#45]
hello, I installed musicrepair correctly with pip3 but when I want to launch the application, the computer tells me this :
`/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

Finished repairing`
 can you help me? I want to use this for my mp3 and this tool can de very useful!
thanks,
beaud37210

**Comment by beaud37210** [comment]
resolved.

**Comment by kalbhor** [comment]
@beaud37210 Could you post what helped you and then close this issue?

**Comment by beaud37210** [comment]
Hello, I forgot to do the config command.

**Comment by beaud37210** [comment]
But is there a function to add album covers?
