### ISSUE TITLE
metadata order incorrect in the song

### ISSUE THREAD

**Issue by JairoQuispe** [kalbhor/MusicRepair#5]
Hi, 

i was trying your script to add metadata with source spotify, but the order of metadata is wrong: 

File: command_line.py - line 228
` def add_details(file_name, song_title, **artist**, **album**, lyrics=""): `

Coukd be replaced with:

def add_details(file_name, song_title, **album**, **artist**, lyrics=""):

Work best.

**Comment by kalbhor** [comment]
Thanks for pointing that out, I've made the necessary changes. It should work fine now.
