### ISSUE TITLE
musicrepair_log.txt is blank

### ISSUE THREAD

**Issue by damenleeturks** [kalbhor/MusicRepair#7]
The log file is being created just fine, but doesn't contain any of the log from the Terminal readout.

**Comment by kalbhor** [comment]
The purpose of the log file is to log the names of the mp3 files that couldn't be repaired. Also, may I know which version of musicrepair you're using? In the latest version, there is a score printed for each mp3 (This score determines how relevant the search results for the mp3 were). If the score is less than 5, musicrepair doesn't repair that file and logs it in the text file.
