### ISSUE TITLE
How to revert the changes?

### ISSUE THREAD

**Issue by damenleeturks** [kalbhor/MusicRepair#8]
Is there a way to revert the changes when the match is wrong?

**Comment by kalbhor** [comment]
I'm trying to implement a feature to do this, but as of now there isn't a way. You'll have to go into your music application like iTunes and manually remove the metadata.

**Comment by kalbhor** [comment]
Could I know the name of the song that fetched the wrong details?

**Comment by kalbhor** [comment]
I have added revert functionality. Check readme for more details. Update musicrepair to obtain the feature. 
To revert metadata, simply put the desired files to be reverted in a folder and then run : 
`musicrepair --revert [folder location]`

**Comment by damenleeturks** [comment]
I know this is closed already, but to answer your question—the ones that fetched the wrong details were personal recordings that happened to be in the same folder as the ones I was trying to add metadata to.

**Comment by kalbhor** [comment]
I don't believe a lot of people will face such a problem of having their personal recordings in the same folder as the music files. Which is why a revert option will do just fine.
