### ISSUE TITLE
Instructions for Windows users

### ISSUE THREAD

**Issue by unquietwiki** [kalbhor/MusicRepair#9]
Just tried this out on Windows, using Python 3.5.2 x64. Here's what I ran into...

* Install Python 3.5 for "all users"; I used the default **C:\Program Files\Python 3.5** location.
* Run **easy_install musicrepair** in an admin command prompt. Pip didn't work.
* **"c:\Program Files\Python35\Scripts\musicrepair.exe"** worked for me, once it installed correctly.

**Comment by kalbhor** [comment]
Forgive me but I couldn't understand the issue. Do you mean that for windows users easy_install works but pip doesn't?

**Comment by unquietwiki** [comment]
@lakshaykalbhor Pip might work, but my first go of it had it stop after some errors on dependencies. Then again, I hadn't tried admin rights on that run. The easy_install run was more complete the first try, before elevating. I've ran into this on other projects: think it has to do with the ability of dependencies to compile stuff with C++ or something.

**Comment by kalbhor** [comment]
I shall add a side note in the readme for windows users that if pip doesn't work, they should try easy_install (With admin rights). Thanks for pointing this out

**Comment by unquietwiki** [comment]
@lakshaykalbhor No problem. 👍 https://packaging.python.org/pip_easy_install/ Seems to indicate whats going on btw.

**Comment by captainwasabi** [comment]
To recursively descend a directory tree this seems to be working:

for /r /d %1 in (*) do musicrepair -d "%1"

**Comment by gautamkrishnar** [comment]
Its because of the python bug https://github.com/pypa/setuptools/issues/398

**Comment by Droyk** [comment]
Hey @uniquetwiki I am sorry to disturb you and ask you will you be able to give me that windows package plz I really want to try this

**Comment by gautamkrishnar** [comment]
@unquietwiki have you checked [Pyintsalller](http://pyinstaller.org/) It allows us to create stand alone distribution of the app

**Comment by unquietwiki** [comment]
@Droyk there's nothing for me to give you, unless you're asking for something to package it up as @gautamkrishnar is suggesting. I just use it on my machine via the easy_install method.

**Comment by botheredbybees** [comment]
When I tried running musicrepair after using the pip install I was getting error message: 

> failed to create process.

It turned out that pip was omitting the quotes around the path to python.
To fix I edited the musicrepair-script.py file to add the quotes:
from:
`#!C:\Program Files (x86)\Python_343\python.exe`
to:
`#!"C:\Program Files (x86)\Python_343\python.exe"`
